version: '3'

services:
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgres://postgres:your_password@db:5432/postgres"
    depends_on:
      - db
    networks:
      - sietos
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=your_password"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - sietos
    deploy:
      restart_policy:
        condition: on-failure

networks:
  sietos:

volumes:
  data: